apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: py-trading-bot
          image: py-trading-bot
          imagePullPolicy: Never
          command: ["/bin/sh", "-c"]
          args: 
            - python manage.py makemigrations;
              python manage.py migrate;
              echo "from django.contrib.auth.models import User; User.objects.create_superuser('$DJANGO_SUPERUSER', 'admin@example.com', '$DJANGO_PASSWORD')" | python manage.py shell;
              python manage.py loaddata dump.json;
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: postgres_user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: postgres_password

            - name: POSTGRES_HOST
              value: py-trading-bot-postgres-service

            - name: REDIS_HOST
              value: py-trading-bot-redis-service
              
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: py-trading-bot-configmap
                  key: postgres_db 

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: secret_key
                                    
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: telegram_token 
                  
            - name: DJANGO_SUPERUSER
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: django_superuser
                  
            - name: DJANGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: django_password    
                          
      restartPolicy: Never
  backoffLimit: 2
