apiVersion: v1
kind: Secret
metadata:
  name: py-trading-bot-secret
type: Opaque
data:
  postgres_user: YWRtaW4= #admin
  postgres_password: YWJjMTIzNA== #abc1234
  secret_key: YWJjMTIzNA== #abc1234 for django
  telegram_token: NTUwODEwMjY5OTpBQUVaTTRXX3VSc05HSUE5UU1NR19Na0c1MTdNN3RvQVJxNAo= #abc1234 for django
  django_superuser: YWRtaW4= #admin
  django_password: YWJjMTIzNA== #abc1234
  
#  REDIS_PASSWORD: ""
