apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-trading-bot-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-trading-bot-postgres-container
  template:
    metadata:
      labels:
        app: py-trading-bot-postgres-container
        tier: backend
    spec:
      containers:
        - name: py-trading-bot-postgres-container
          image: postgres:15.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: postgres_user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: py-trading-bot-secret
                  key: postgres_password

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: py-trading-bot-configmap
                  key: postgres_db

          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: py-trading-bot-postgres-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: py-trading-bot-postgres-service
spec:
  selector:
    app: py-trading-bot-postgres-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: py-trading-bot-postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/py-trading-bot-postgres-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: py-trading-bot-postgres-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: py-trading-bot-postgres-pv
