apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-trading-bot-redis
  labels:
    app: py-trading-bot-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: py-trading-bot-redis
  template:
    metadata:
      labels:
        pod: py-trading-bot-redis
    spec:
      containers:
        - name: py-trading-bot-redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: py-trading-bot-redis-service
spec:
  selector:
    pod: py-trading-bot-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: NodePort   
